/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_lizhiduo_ffmpegtest_utils_jniUtils */

#ifndef _Included_com_example_lizhiduo_ffmpegtest_utils_jniUtils
#define _Included_com_example_lizhiduo_ffmpegtest_utils_jniUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_lizhiduo_ffmpegtest_utils_jniUtils
 * Method:    checkID
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_example_lizhiduo_ffmpegtest_utils_jniUtils_checkID
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
